import type { Metadata } from "next";

/**
 * The one origin every canonical, sitemap entry, feed link and structured-data URL is built
 * from. It must be the host Vercel actually serves with a 200: today the bare domain
 * redirects to www, so www is canonical. If the primary domain is ever flipped in the
 * Vercel dashboard, change it here and nowhere else.
 */
export const SITE_URL = "https://www.overninethousand.com";
export const SITE_NAME = "OverNineThousand";
export const SITE_DESCRIPTION =
  "OverNineThousand is the studio of Joseph Sebastian Ruiz, a freelance fullstack developer in Los Angeles building Flutter mobile apps, .NET APIs and Angular/React websites. Maker of Psychic Tournament.";

export const AUTHOR = {
  name: "Joseph Sebastian Ruiz",
  alternateName: "SupaSebie",
  jobTitle: "Freelance Fullstack Developer",
  email: "overninethousanddevelopment@gmail.com",
  sameAs: ["https://github.com/supasebie", "https://www.linkedin.com/in/jsebastianruiz/"],
};

export const PSYCHIC_TOURNAMENT = {
  url: "https://psychictournament.online/",
  googlePlayUrl: "https://play.google.com/store/apps/details?id=com.overninethousand.psychictournament",
  appStoreUrl: "https://apps.apple.com/us/app/psychic-tournament/id6806195000",
};

/** Appended to every page title except the home page's. */
export const TITLE_TEMPLATE = `%s | ${SITE_NAME}`;

/**
 * The site-wide share card generated by app/opengraph-image.tsx. Pages that set their own
 * `openGraph` must list it explicitly: Next replaces the parent's openGraph object, image
 * included, instead of merging into it.
 */
export const DEFAULT_OG_IMAGE = {
  url: "/opengraph-image",
  width: 1200,
  height: 630,
  alt: "OverNineThousand: freelance fullstack and mobile app development",
};

export function absoluteUrl(path = "/"): string {
  return new URL(path, SITE_URL).toString();
}

type PageMetadataInput = {
  title: string;
  description: string;
  /** Site-relative path of the page, e.g. "/tools/dev/base64". Becomes the canonical URL. */
  path: string;
  keywords?: string | string[];
  type?: "website" | "article";
  publishedTime?: string;
  images?: { url: string; width?: number; height?: number; alt?: string }[];
  noIndex?: boolean;
};

/**
 * Metadata for a single page. Always sets a self-referencing canonical, and repeats the
 * site-wide Open Graph fields because Next replaces a parent's `openGraph` object wholesale
 * rather than merging into it.
 *
 * The title is passed as `{ default, template }` rather than a string: a plain string title
 * in a layout resets the template for everything beneath it, which dropped the site name
 * from pages nested under a tool's layout.
 *
 * A layout may use it only if every page beneath it sets its own canonical: a canonical set
 * in a layout is inherited by any child that doesn't, pointing them all at the parent.
 */
export function pageMetadata({
  title,
  description,
  path,
  keywords,
  type = "website",
  publishedTime,
  images,
  noIndex,
}: PageMetadataInput): Metadata {
  const shareImages = images ?? [DEFAULT_OG_IMAGE];

  return {
    title: { default: title, template: TITLE_TEMPLATE },
    description,
    ...(keywords && { keywords }),
    alternates: { canonical: path },
    openGraph: {
      title,
      description,
      url: path,
      siteName: SITE_NAME,
      locale: "en_US",
      type,
      ...(type === "article" && publishedTime && { publishedTime, authors: [AUTHOR.name] }),
      images: shareImages,
    },
    twitter: {
      card: "summary_large_image",
      title,
      description,
      images: shareImages.map((image) => image.url),
    },
    ...(noIndex && { robots: { index: false, follow: true } }),
  };
}
